### ISSUE TITLE
Be able to specify initial value for LFSR16

### ISSUE THREAD

**Issue by edwardcwang** [freechipsproject/chisel3#1003]
**Type of issue**: feature request

**Impact**: API addition (no impact on existing code)

**Development Phase**: proposal

**Other information**:

Chisel3 utils' LFSR16 hardcodes the initial value to 1 as opposed to leaving it a parameter. It seems useful to be able to optionally choose the initial value.

https://github.com/freechipsproject/chisel3/blob/e564fff139768e6a232d118ec7155ecf080f1bc4/src/main/scala/chisel3/util/LFSR.scala#L22

**Comment by azidar** [comment]
New LFSR takes seeds.
