### ISSUE TITLE
Vec of modules incorrectly passing paramaters

### ISSUE THREAD

**Issue by coogsie** [freechipsproject/chisel3#1012]
Parametrized modules are throwing an error when making a vector of them.

`
val foo = Vec( Seq.fill( count ){ Module( new bar( paramA, paramB )  ).io } ) //Throws error
val buzz = Module ( new bar( paramA, paramB ) //Works fine
`

Looking at the error it seems to be that the paramaters aren't being correctly being passed down as SBT complains that they aren't both immutable and accessible.

**Comment by edwardcwang** [comment]
Hi there, and thank you for your interest in Chisel!

A `Vec` in Chisel is a type (like `UInt`, `Bool`, etc). For this reason, we can only have `Vec of <type>` not `Vec of <piece of hardware e.g. Mux, Module, etc>`. It is the same reason we can't have "Vec of Registers" in Chisel: https://github.com/freechipsproject/chisel3/wiki/Cookbook#how-do-i-create-a-vector-of-registers

**Comment by coogsie** [comment]
Hi, the way you are using is different to that of the UCB Chisel wiki (https://github.com/ucb-bar/chisel-tutorial/wiki/instantiating-modules)

`val foo = Vec(Seq.fill(16){ Module(new bar( i ) ).io } )`
vs
`val foo = (0 until 10).map { i => Module(new bar( i ) ) }`

If the way you specified is the correct way then I apologize, I am still learning the nuances of Chisel and Scala.

**Comment by edwardcwang** [comment]
So the former creates a `Vec of <bar io>`, where `<bar io>` is (typically) a Bundle defining the IOs of the module `bar`, whereas the latter creates a Scala `Seq` of Modules. You can transform the latter into the former via `Vec(foo.map(_.io).toSeq)`. It's just that the `Vec` itself can't be  dependent upon arbitrary hardware.

**Comment by edwardcwang** [comment]
Please feel free to re-open or leave a comment if you have any further questions.
