### ISSUE TITLE
Better debug visibility / error messages for chiselName

### ISSUE THREAD

**Issue by edwardcwang** [freechipsproject/chisel3#1046]
It should only be used to annotate hardware generation code. Basically, annotated functions will crash if invoked outside a Builder context - because names can't be generated in those cases.

We can think about improving debug visibility, though. Possibilities:
- Improving the error message when a transformed method is invoked outside a Builder context, so that it's more obvious that it's caused by chiselName.
- Having it fail silently when invoked outside a Builder context.

_Originally posted by @ducky64 in https://github.com/freechipsproject/chisel3/pull/1045#issuecomment-475457792_

**Comment by ducky64** [comment]
Resolution from today's meeting is to take path 2, failing silently when invoked outside a Builder context. Reasoning:
- allow writing Modules (or similar) that mix Chisel HDL and other functionality like testdriver code
- chiselName is best-effort anyways and should not affect correctness
