### ISSUE TITLE
@chiselName on a Module with a nested ChiselEnum results an error

### ISSUE THREAD

**Issue by kammoh** [freechipsproject/chisel3#1100]
**Type of issue**: bug report

**Impact**: unknown

**Development Phase**: request

**Other information**
 

Applying `@chiselName` annotation on a `Module` with a `ChiselEnum` object results in compilation error.

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

``` scala
@chiselName
class MyModule extends MultiIOModule {
  object State extends ChiselEnum {
    val x, y, z = Value
  }
}
```

Scala compile error:
`Error: Value cannot be called without assigning to an enum
    val x, y, z = Value
`
**What is the current behavior?**

**What is the expected behavior?**

**Please tell us about your environment:**

- version: `3.0-SNAPSHOT`
- OS: `macOS`

**What is the use case for changing the behavior?**

**Comment by hngenc** [comment]
It seems the problem is that @chiselName will change `val x = Value` to `val x = context.name(Value, x)`, at least judging by this line: https://github.com/freechipsproject/chisel3/blob/820e2688f0cb966d4528ff074fdbdc623ed8f940/coreMacros/src/main/scala/chisel3/internal/sourceinfo/NamingAnnotations.scala#L156

**Comment by ducky64** [comment]
That sounds like a reasonable root-cause - the chiselName macro really mostly is a simple rewrite that adds a `context.name` call to anything of the form `val name = expr`. Blacklisting `Value` would be one possible solution, though it's not a selective / general one. Thoughts? Perhaps if type information is available to macros, we could whitelist only expressions that type to Data?

**Comment by hngenc** [comment]
My plan was to change the `Value` macro so that it also recognizes statements of the form `val x = foo(x, ...)`. Macros can be tricky, but I think that would be possible.
