### ISSUE TITLE
What doew the operator '<>' mean?

### ISSUE THREAD

**Issue by myuanqing** [freechipsproject/chisel3#1101]
Is there any differences between '<>' and ':='?

**Comment by edwardcwang** [comment]
Hi there,

Thank you for your interest in Chisel! `<>` is a bulk-connect operator; you can find out more about it here: https://github.com/freechipsproject/chisel3/wiki/Interfaces-Bulk-Connections#bulk-connections

Please feel free to open a new issue if you experience any bugs.
