### ISSUE TITLE
Is there a quick method to  initialize all register with zero by reset signal rather than system function $random?

### ISSUE THREAD

**Issue by 245950258** [freechipsproject/chisel3#1102]
I can use the Reginit method to initialize register with the value I want. However, there are a large number of registers, so is there a method to solve this?

**Comment by grebe** [comment]
You could write a firrtl pass that goes through every uninitialized register and gives them an initialization to zero. There is an introduction to writing firrtl passes in [the bootcamp](https://github.com/freechipsproject/chisel-bootcamp/) (see section 4) and [some wiki information](https://github.com/freechipsproject/firrtl/wiki/Transform-Writing-Manual).
