### ISSUE TITLE
chisel cheatsheet link in README.md needs update

### ISSUE THREAD

**Issue by egaburov** [freechipsproject/chisel3#1169]
“Cheat Sheet, a 2-page reference of the base Chisel syntax and libraries” link in README.md  gives 404: https://chisel.eecs.berkeley.edu/doc/chisel-cheatsheet3.pdf

**Comment by seldridge** [comment]
Thanks for your interest in Chisel and for reporting this! We just switched to a new website and not all the links were properly preserved (apparently).

I'll get this up on the new website and update the README.md. In the meantime, if you need to access the cheatsheet, I've attached a version to this comment.
[cheatsheet3.pdf](https://github.com/freechipsproject/chisel3/files/3564392/cheatsheet3.pdf)
