### ISSUE TITLE
posedge memory 

### ISSUE THREAD

**Issue by sajjadahmed677** [freechipsproject/chisel3#1204]
how can i synchronize memory with posedge in chisel3

**Comment by ekiwi** [comment]
Try using a [SynchReadMem](https://github.com/freechipsproject/chisel3/blob/fddb5943b1d36925a5435d327c3312572e98ca58/chiselFrontend/src/main/scala/chisel3/Mem.scala#L132)

**Comment by ekiwi** [comment]
Let us know if you have any other questions.
