### ISSUE TITLE
Nested @chiselName adds extra names

### ISSUE THREAD

**Issue by jackkoenig** [freechipsproject/chisel3#1371]
**Type of issue**: bug report

**Impact**: no functional change

**Development Phase**: request

**Other information**
 

I have confirmed this is caused by https://github.com/freechipsproject/chisel3/pull/1209 by reverting 9406e2bb5fa0a99f26f601a2f77db31f5598fc3b and seeing that it fixes the problem.

To be clear, I do **not** think we should revert #1209, but I think we should fix this before releasing 3.3.

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

Given the following nested use of `@chiselName`:
```scala
import chisel3._
import chisel3.experimental.chiselName

@chiselName
class MyModule extends Module {
  val io = IO(new Bundle {
    val in = Input(UInt(8.W))
    val out = Output(UInt(8.W))
  })
  @chiselName class NamingDomain {
    val myReg = RegNext(io.in)
    io.out := myReg
  }
  val domain = new NamingDomain
}

object MyMain extends App {
  chisel3.Driver.execute(args, () => new MyModule)
}
```
This may look funky, but the outer `@chiselName` does not name the stuff inside `NamingDomain` and this pattern is useful for constructing domains for use in `withClockAndReset` domains, (eg. https://github.com/chipsalliance/rocket-chip/blob/8af2eb0aadb3bb3bb0f44c400e1ff36ed50f349c/src/main/scala/rocket/DCache.scala#L112)

**What is the current behavior?**

If you run this with master (1a4e0dd65ba3e64268beca8f592bd58d98c434a4) you'll get:
```
circuit MyModule : 
  module MyModule : 
    input clock : Clock
    input reset : UInt<1>
    output io : {flip in : UInt<8>, out : UInt<8>}
    
    reg domain_myReg : UInt, clock
    domain_myReg <= io.in
    io.out <= domain_myReg
```

**What is the expected behavior?**

If you run with `v3.2.3` you get:
```
circuit MyModule : 
  module MyModule : 
    input clock : Clock
    input reset : UInt<1>
    output io : {flip in : UInt<8>, out : UInt<8>}
    
    reg myReg : UInt, clock
    myReg <= io.in
    io.out <= myReg
```

**What is the use case for changing the behavior?**

The `v3.2.3` behavior is the desired behavior.

**Comment by jackkoenig** [comment]
I now see that this is intentional behavior introduced by #1209, from the tests:
```scala
@chiselName
class OuterNamedNonModule {
  val value = Wire(Bool())
}

@chiselName
class NonModule {
  val value = Wire(Bool())
  @chiselName
  class InnerNamedNonModule {
    val value = Wire(Bool())
  }
  val inner = new InnerNamedNonModule
  val outer = new OuterNamedNonModule
}

.
.
.

  val test4 = new NonModule
  expectName(test4.value, "test4_value")
  expectName(test4.inner.value, "test4_inner_value")
  expectName(test4.outer.value, "test4_outer_value")
```

Is this actually the behavior we should desire? I will grant that one could remove the inner `@chiselName` in my example above, but even with the `test4_value`, how can you express that you just wanted it to be `value`?

Thoughts @ducky64 @johnsbrew?

**Comment by ducky64** [comment]
I think the fully qualified name is needed, otherwise you can get naming conflicts because there's no expectation that leaf-level names not conflict with each other. I think the fully qualified name should be the default, but perhaps some way to drop a specific name component might be useful?

**Comment by jackkoenig** [comment]
I'm okay with a way to drop it, but we definitely need it, maybe it could be an argument to the `@chiselName` macro?
```scala
@chiselName(stripPrefix=true)
```
or something

**Comment by ducky64** [comment]
Is it the usual case where you want to flatten all of a kind of Module (which would the effect of having an argument to `@chiselName` - it's associated with a Module definition) rather flattening a specific instantiation (and where the writer of the enclosing Module will be able to better deal with naming conflicts)? In the example use case of a class as an organizational unit, where it is only instantiated once, both are probably equivalent, but that might not generalize?

**Comment by jackkoenig** [comment]
Being able to express it on a per-instantiation basis would probably be the most flexible option, but I'm not really sure how that API would work with a macro.

This case is certainly fine with the flattening all instances, and honestly I can't think of a case where you would want to flatten on a case-by-case basis, but if we can do the more flexible thing in a reasonable way we probably should.

**Comment by ducky64** [comment]
A rough sketch of the proposal I briefly talked about at the meeting today:
```scala
import chisel3.experimental.StripNamePrefix
...
@chiselName class MyOuterModule {
  @chiselName class MyInnerModule {
    ???
   }
  val inner = StripNamePrefix(Module(new MyInnerModule))
}
```

What `StripNamePrefix` (feel free to suggest better names) would do would be to remove the prefix for the single child Module, so this would give fine-grained control to where you do or don't want a prefix. For now, this can be a chiselName-only function (so using it in a non-chiselName context could error - the chiselName transform could remove StripNamePrefix, whereas actually having it invoked in code would be a runtime error), and the naming transform can match on StripNamePrefix and generate a different Named(...) call. It can also fail on leaf-level nodes.

I think it would make sense for StripNamePrefix to only apply to the immediate naming level, but I could see an argument made for removing prefixes all the way down to the leaf node. But it's experimental, we've got leeway. It's probably also the right approach given the urgency of fixing this.

**Comment by johnsbrew** [comment]
Hey @jackkoenig 
Sorry for not responding earlier, I didn't see your post ... neither did I catch the on-going discussion at the dev meeting while I was there!

At the first glance it sounded quite funny that you report as a bug a feature you actually agreed with a few months ago ;-)

That being said, I understand your need for a fine control over the naming in some cases (it could become quite huge names in the end if there are many nested modules...)

The solution reported by @ducky64  you came up with at the dev meeting sounds quite nice.

I wonder if mixing in a very simple trait `NoNamePrefix` with the class would constitute an interesting alternative? simpler to implement or not? I am not really aware of scala macro howtos and it would restrict the control grain to class instead of instances.

**Comment by jackkoenig** [comment]
Originally I thought that the stuff in rocket-chip was unaffected, I actually thought it just had the outer `@chiselName` and that the old behavior was supported that way.

In any case, a mixin is an interesting idea because it could be applied for all instances of a class as well as only at use eg.
```
val inner = Module(new MyInnerModule extends StripChiselNamePrefix)
```
In any case, both reasonable things to try.
