### ISSUE TITLE
Private vals don't get named by reflection nor @chiselName

### ISSUE THREAD

**Issue by jackkoenig** [freechipsproject/chisel3#1410]
The most egregious example is in `Queue` which uses private vals. Now perhaps we should just make them public, but the issue still stands.

Long ago, Chisel reflective naming worked on `private val` (https://github.com/freechipsproject/chisel3/pull/407), it seems this is no longer true.

It's also of note that `@chiselName` doesn't name private vals.

I feel like both of these are bugs that should be fixed.

**Type of issue**: bug report

**Impact**:  API addition (no impact on existing code)

**Development Phase**: request

**Comment by mwachs5** [comment]
There was a workaround for some other issue that was relying on this behavior.... let me find which one it is

**Comment by seldridge** [comment]
(Having not tested it and just looking through issues/PRs...) How does the Chisel naming plugin handle this? Does that close this issue?

**Comment by jackkoenig** [comment]
Just checked, the plugin does indeed handle this!

Fixed by https://github.com/freechipsproject/chisel3/pull/1448
