### ISSUE TITLE
I am newbee here. I want to find a IDE which can "ctrl + click" to jump the define code 

### ISSUE THREAD

**Issue by xinlnix** [freechipsproject/chisel3#1477]
Just want to find IDE

**Comment by sequencer** [comment]
Intellij IDEA may be good for you

**Comment by ducky64** [comment]
For reference, of the chisel developers who use IDEs, most (if not all?) use IntelliJ. It has a Scala plugin which is pretty good.

**Comment by danielkasza** [comment]
Visual Studio Code with the "Scala (Metals)" plugin works for me so far. IntelliJ is also good, but I like the vscode interface more.

**Comment by seldridge** [comment]
Expanding on @danielkasza's suggestion: any editor that supports Scala metals should work. And it looks like most editors support "go to definition": https://scalameta.org/metals/docs/editors/overview.html. I'd grab one of those, install metals and see where it gets you.

I'll go ahead and close this as I think this is sufficiently answered. In the future, questions like this would probably be better targeted at [StackOverflow using the `[chisel]` tag](https://stackoverflow.com/questions/tagged/chisel) or brought up in the [Gitter Channel](https://gitter.im/freechipsproject/chisel3) or it's [Matrix bridge](https://riot.im/app/#/room/#chisel:matrix.org). It's all good, though! :+1: Thanks for your interesting in getting started with Chisel.
