### ISSUE TITLE
Cat of 0 element Vec throws exception on empty.tail

### ISSUE THREAD

**Issue by hcook** [freechipsproject/chisel3#1622]
**Type of issue**: bug report 

**Impact**: no functional change 

**Development Phase**: request 

**Other information**

**If the current behavior is a bug, please provide the steps to reproduce the problem:**
https://scastie.scala-lang.org/ez6cIEduSkyz9hoct60urg

**What is the current behavior?**

Using the `Cat` operator on a `Vec` with zero elements throws an exception `java.lang.UnsupportedOperationException: empty.tail`

**What is the expected behavior?**

I would expect to get back an equivalent zero element `Vec`.

**Please tell us about your environment:**
https://scastie.scala-lang.org/ez6cIEduSkyz9hoct60urg

**What is the use case for changing the behavior?**
I don't want to have to write if statements guarding all my cats.

**Comment by seldridge** [comment]
@hcook: Do you expect this to be a zero-element `Vec` or a `0.U`? I think you actually mean the latter here?

Thanks for the test case. That module name needs to be preserved for prosperity.

**Comment by hcook** [comment]
Ahaha I was copying one of @jackkoenig's scastie examples and just left it. The original was pretty impressive tbf.

You're right that `0.U` is the most sensible output.
