### ISSUE TITLE
BuildInfo API

### ISSUE THREAD

**Issue by grebe** [freechipsproject/chisel3#335]
Chisel now spits out a nice string at the top of generated firrtl with some build information. I think it would be nice to have a standard way of adding more build information about e.g. library versions, seeds.

@chick and @ucbjrl and I talked some about how the sbt-buildinfo plugin works and the possibility of using reflection for chisel to grab all the BuildInfo objects out there.

I also found this potential problem:  sbt/sbt-buildinfo#97

**Comment by ducky64** [comment]
Apparently fixed.
Future requests for updating this API should include a use case as a driving example.
