### ISSUE TITLE
ScalaDoc Improvements to Utils

### ISSUE THREAD

**Issue by jackkoenig** [freechipsproject/chisel3#411]
The chisel3 ScalaDoc needs some cleaning up.

chisel3.util (Note these are done by file in src/main/scala/chisel3/util)
- [x] Arbiter through CircuitMath - @ducky64 
- [ ] CircuitMath through ImplicitConversions - @donggyukim 
- [ ] LFSR through OneHot - @davidbiancolin 
- [ ] Reg through util - @jackkoenig

chisel3.core
- [x] Vec - @chick 
- [x] Bundle - @chick 

Recall the discussion in #398 that examples belong on the class if it exists, the object otherwise. On apply methods and the like, just document what the different parameters are. For inspiration, look at [Scala List](http://www.scala-lang.org/api/current/scala/collection/immutable/List.html).

Feel free to suggest more items to add.

**Comment by ducky64** [comment]
*poke*

**Comment by ducky64** [comment]
Skimmed through the contents of utils, and everything looks documented. Once the final fixes from #1015 are merged we can close this,
