### ISSUE TITLE
Expose invalidate API and stop invalidating everything by default

### ISSUE THREAD

**Issue by jackkoenig** [freechipsproject/chisel3#413]
It is safer to error when things are left unconnected. For use cases where various things are expected not to be connected, the user can explicitly invalidate Chisel *values* (not *types*).

**Comment by ucbjrl** [comment]
I've started a Google Doc for the [Invalidate API](https://docs.google.com/a/berkeley.edu/document/d/1EzhXL5EMw8vQMNppmqVNJC4qVyEST7tKzW9YBNamIOo/edit?usp=sharing). Please comment or edit that document. Once we've reached an internal consensus, we'll publish the content for public comment.

**Comment by colinschmidt** [comment]
Presumably this wont affect code that doesn't import chisel3._

**Comment by jackkoenig** [comment]
This will not affect the compatibility wrapper. It is intended to be improved safety for users of chisel3._

**Comment by ucbjrl** [comment]
Fixed by #645
