### ISSUE TITLE
setBinaryPoint

### ISSUE THREAD

**Issue by shunshou** [freechipsproject/chisel3#513]
```
def do_setBinaryPoint(that: Int)(implicit sourceInfo: SourceInfo): FixedPoint =
    binop(sourceInfo, FixedPoint(this.width, KnownBinaryPoint(that)), SetBinaryPoint, that)
```

@chick @azidar this is the problem I was mentioning earlier. If that is > this.binaryPoint, width needs to be this.width + (that - this.binaryPoint)... I'm not sure how Chisel deals with this + if this.binaryPoint is unknown? Maybe it should just return unknownWidth?

**Comment by azidar** [comment]
Yes, we should return unknownWidth if this.binaryPoint is unknown.

Another thought - can we get rid of setBinaryPoint by just calling AsFixedPoint instead?

**Comment by shunshou** [comment]
If AsFixedPoint gives you the right functionality? If I take some fixed point number f, can I do f.AsFixedPoint(BP = 5), say when originally f had 3 fractional bits, and have it add 2 fractional bits + increase with to original width + 2? If so, then yes. If it doesn't do what I want, then no? lol

**Comment by azidar** [comment]
Oh right, this is different behavior. Lol forget I mentioned it.

**Comment by shunshou** [comment]
Prob means a better name should be thought up if the meaning isn't well conveyed :p

**Comment by azidar** [comment]
Can you give me a snippet of chisel3 code that exercises this bug please?

**Comment by shunshou** [comment]
```
  val test = Wire(FixedPoint(10.W, 5.BP))
  val q = test.setBinaryPoint(18)
  println(q.getWidth)
```

Width should be 10+13, instead it returns 10.

**Comment by ducky64** [comment]
Appears fixed,
