### ISSUE TITLE
A simple proposal for better generated names

### ISSUE THREAD

**Issue by ben-k** [freechipsproject/chisel3#535]
Although Chisel3 naming is definitely improving, I still find myself having to grep through the generated Firrtl for a wire/reg/module/etc. named `_T*` every so often.

This process would be a bit more user friendly if the Chisel-generated names were distinguished by type.  So wires could be named `_W*`, registers `_R*`, modules `_M*`, and so forth.

I imagine (hope) this would not be a burdensome change, and it would definitely improve readability and ease my use case.

See also my related Firrtl request: ucb-bar/firrtl#469

**Comment by aswaterman** [comment]
Seems reasonable to me.  Would also have the effect of making temp naming for registers and memories ever-so-slightly more stable, since the majority of temps are wires.

**Comment by jackkoenig** [comment]
I agree with the suggestion, one thing to note:

Modules *should* already be named based on the name of the Module itself. If this is not the case, it is a bug.

**Comment by aswaterman** [comment]
when I first skimmed the proposal I assumed _M was for memories... which it should be.

**Comment by colinschmidt** [comment]
This specific case of a module with a _T name is a SeqMem that becomes a module during ReplSeqMem, so the _M stands for memory.

**Comment by jackkoenig** [comment]
This was done in `v3.4.0`
