### ISSUE TITLE
Add assertion example to Wiki

### ISSUE THREAD

**Issue by mwachs5** [freechipsproject/chisel3#540]
The Wiki has examples of how to print, but not write assertions. My assertions recently stopped compiling, perhaps because of #500 ? What is the right way to do something like:

`assert (a === b, "A (%x) is not equal to B (%x) !", a, b)`

If I do this I get errors like:

```
Caused by: java.lang.IllegalArgumentException: requirement failed: Too many arguments! More format specifier(s) expected!
    fmt = "A (%%x) is not equal to B(%%x)!"
...
```

**Comment by jackkoenig** [comment]
Whoops. This is my fault. We do need examples but this should not have stopped working. I think the fix shouldn't be too bad.

**Comment by jackkoenig** [comment]
Can you try https://github.com/ucb-bar/chisel3/pull/542 to see if it fixes your broken assertions?

**Comment by mwachs5** [comment]
Yes it fixes my issue
