### ISSUE TITLE
Matching on Input

### ISSUE THREAD

**Issue by shunshou** [freechipsproject/chisel3#543]
For p: Element, I wanted to do something like:

```
p.dir match {
      case Input => println("xxx")
      case Output => println("yyy")
 }
```
But even when p.dir is Input or Output, this match will throw an exception. In reality, it looks like you need to do:

```
p.dir match {
      case chisel3.core.Direction.Input => println("xxx")
      case chisel3.core.Direction.Output => println("yyy")
    }
```

Pretty big gotcha imo :(

**Comment by chick** [comment]
Won't fix, directions are sealed so compiler should warn you
