### ISSUE TITLE
Vecs lose direction in compatibility mode

### ISSUE THREAD

**Issue by ucbjrl** [freechipsproject/chisel3#625]
OpenSoc contains chisel2 code such as:
```
      val wePipelineReg = Vec(pipelineDepth, Bool(INPUT) )
      ...
      headFlitRegFile.io.wePipelineReg(0)      := (!headFlitRegFile.io.rvPipelineReg(0)) && headFlitRegFile.io.readValid

```

This loses the `INPUT` direction as a result of PR #344, and generates a firrtl error:
```
firrtl.passes.CheckGenders$WrongGender:  @[router.scala 530:66]: [module SimpleVCRouter]  Expression RouterRegFile.io.wePipelineReg[0] is used as a FEMALE but can only be used as a MALE.
```
I'm not sure what the correct solution is here. Possibly:
```
      val wePipelineReg = Vec(pipelineDepth, Bool() ).asInput
```
At the very least we should add this to the documentation on converting from chisel2 to chisel3 and diagnose this as a chisel2 compatibility mode warning/error.

**Comment by ducky64** [comment]
This bug has been inactive for a while and there has been significant refactoring on the directions / bindings system since. If this is still an issue, feel free to re-open.
