### ISSUE TITLE
Documentation needed on how Chisel/FIRRTL width-inference works

### ISSUE THREAD

**Issue by ccelio** [freechipsproject/chisel3#650]
Related: #649

The fact that Chisel (or perhaps rather FIRRTL) width inference is forward propagating needs to be documented.

For example: 
* The Chisel [FAQ](https://github.com/freechipsproject/chisel3/wiki/Frequently-Asked-Questions)
* [A short user guide to chisel](https://github.com/freechipsproject/chisel3/wiki/Short-Users-Guide-to-Chisel)

The only documentation I found is [Getting Started](https://chisel.eecs.berkeley.edu/2.2.0/getting-started.html) from 2015, but is a bit buried.

**Comment by jackkoenig** [comment]
I think is super important to 3.0.0 since it is a key part of the API that needs to be formally described and tested.

I brought this up a while ago (https://github.com/freechipsproject/chisel3/pull/455#discussion_r101434653) but it got put on the back burner a bit.

**Comment by chick** [comment]
I updated the section on width inference in the chisel3 wiki, last week.  I also referred reader to the firrtl spec, which should probably be the final formal arbiter on how this works
