### ISSUE TITLE
On the deprecation of log2Up

### ISSUE THREAD

**Issue by da-steve101** [freechipsproject/chisel3#652]
1) I don't think log2Up should reference log2Ceil in the deprecation warning. log2Ceil( 0 ) = 0 but log2Up( 0 ) = 1 so slightly different functionality.
2) As these are functionally different, I am in favour of keeping log2Up within chisel3

**Comment by ducky64** [comment]
See #528 for a rationale of why, log2Up was originally introduced to work around the lack of zero width wires, a feature which now exists and should present a cleaner solution.

Is there a particular reason (not addressed above) that you want to keep using log2Up for?

**Comment by da-steve101** [comment]
It is related to that i guess. I can see the point of deprecating it. I was just frustrated when I changed my code log2Ceil and then some of my stuff broke when i was using:
```scala
val xVal = 0
val x = xVal.U( log2Up( xVal ).W )
val x = xVal.U( log2Ceil( xVal ).W )
```

**Comment by jackkoenig** [comment]
Do you need to declare the width or would your code work just fine letting
it be inferred since it's a literal?

Also is putting 0 as the width failing? Supporting 0 as the width is part
of supporting of zero-width wires.

**Comment by da-steve101** [comment]
no zero width is fine, but declaring 0 with a width of zero results in "insufficient bits" error. Yeah I could. It was chisel2 code and i just did a find and replace.

**Comment by jackkoenig** [comment]
So are you still arguing for keeping log2Up or should I close this issue?

**Comment by jkorinth** [comment]
Still, currently `log2Ceil(1) == 0`, which seems like a bug? It broke some of my bundles, e.g., when declaring a 1-bit input as `val x = Input(UInt(log2Ceil(someValue).W))` and having `someValue == 1` makes `x` disappear from the bundle completely (leading to further errors in `PeekPokeTester` etc.).
