### ISSUE TITLE
error when declare a flip bundle

### ISSUE THREAD

**Issue by apolonic** [freechipsproject/chisel3#663]
[error] my.scala:115: Parameterized Bundle class my_IO needs cloneType method in class my_class

workaround if you bundle takes parameter(s) and use its flip bundle, you can clone the type when you define that bundle:
override def cloneType = new your_bundle(your_param).asInstanceOf[this.type]

**Comment by ducky64** [comment]
Should be vastly improved with #669, the described workaround should be documented in the error message
