### ISSUE TITLE
Documentation Needed for RawModule and MultiIOModule

### ISSUE THREAD

**Issue by chick** [freechipsproject/chisel3#678]
There is no real description in the Wiki on RawModule or MultiIOModule.  We should make
some.  It's possible there should be a section on Experimental, particularly for those features that we would like developers to try out.

**Comment by Martoni** [comment]
Has a reference, there is an answered question about [RawModule on stackoverflow](https://stackoverflow.com/questions/41427717/how-to-delete-clock-signal-on-chisel3-top-module). And discussion about this feature [are here](https://github.com/freechipsproject/chisel3/pull/469).

**Comment by Martoni** [comment]
I just made a push commit for [documentation proposal](https://github.com/freechipsproject/www.chisel-lang.org/pull/24).
