### ISSUE TITLE
Generation of harness code with verilator

### ISSUE THREAD

**Issue by da-steve101** [freechipsproject/chisel3#680]
I have some tests of the form
```scala
for ( paramSet <- paramList ) {
  Driver... blah blah create new module using paramSet
}
```
Essentially the number of inputs/outputs from the tester I am using ( PeekPoke ) changes.
It appears the harness code is not regenerated so I get all these compile errors with "no member named ... "
Its just verilator ... firrtl seems to be fine.

**Comment by azidar** [comment]
Conclusion: define a methodology for integrating scalacheck with testers.

**Comment by azidar** [comment]
stale, unclear example. Please reopen if still desired.
