### ISSUE TITLE
Needs cloneType for ArbiterIO

### ISSUE THREAD

**Issue by kriszhyan** [freechipsproject/chisel3#690]
I just started using Chisel3. The following code complains about the lack of `cloneType` for `ArbiterIO`.
```
class Test[T <: Data](gen: T, n: Int) extends Module {
  val io = IO(new Bundle {
    val x = Input(Bool())
    val y = Output(Bool())
  })
  val arbIO = Vec.fill(n) {Module(new RRArbiter(gen, n)).io}
}
```
But if I wrote
```
  val arb = Seq.fill(n) {Module(new RRArbiter(gen, n))}
```
No error would be reported.

A similar issue was discussed in #245 with a fix dfc7f21. I guess this issue can also be fixed by adding a `cloneType` method to `ArbiterIO`. If that's desirable, I can make a pull request.

On the other hand, I don't understand why the second approach works without the need of a `cloneType` method. Can anyone explain a bit?

**Comment by ducky64** [comment]
This should be fixed by autoclonetype.
I think the two different behaviors you observed also has to do with IOs not cloning, which has also since been fixed.
