### ISSUE TITLE
chisel.eecs.berkeley.edu refused to connect.

### ISSUE THREAD

**Issue by francisdb** [freechipsproject/chisel3#692]
Has the website moved somewhere else?

**Comment by ucbjrl** [comment]
We were undergoing general maintenance on the internal network. The website should be back online.

**Comment by chick** [comment]
I believe the system was down due to some maintenance work.  Please try
again, it is working now
Cheers,
-chick

Chick Markley
Staff Programmer -- Aspire Lab
University of California, Berkeley
583-2 Soda Hall, Berkeley, CA 94720-1776
chick@berkeley.edu
