### ISSUE TITLE
Incorrect Wiki Article

### ISSUE THREAD

**Issue by jessedog3** [freechipsproject/chisel3#696]
The [Combinational Circuits](https://github.com/freechipsproject/chisel3/wiki/Combinational-Circuits) article in the wiki gives the following example:

    val myNode = Wire(UInt(8.W))
    when (isReady) {
      myNode := 255.U
    } .elsewhen {
      myNode := 0.U
    }

The .elsewhen should be a .otherwise
(perhaps an additional example demonstrating .elsewhen should be added? It isn't mentioned in the rest of the wiki).

**Comment by edwardcwang** [comment]
Great catch, thanks! It should be fixed now (and added an additional example of .elsewhen).
