### ISSUE TITLE
Comparison Operators should check whether widths allow both outcomes.

### ISSUE THREAD

**Issue by chick** [freechipsproject/chisel3#697]
It would be nice if comparison operators could check information available to their operands that would determine if both outcomes of the operator are possible.
A  common early programming error in chisel is.
```scala
val counter = RegInit(0.U)
when(counter > 15.U) {
  ???
}
```
```counter``` above cannot get bigger than 1 since it's width was not set explicitly and thus the when block will never be executed.  I don't know if this might be a new feature of *constant propagation* or maybe *dead code elimination* but I think this would help cut off a number of easily made errors.

**Comment by ccelio** [comment]
Chisel, at its heart, is a generator language. We (and every other language) already remove dead code that a user may have intended to hook up, and I see this as the same situation.

With that in mind, it would be nice to provide the user a way to check for coding errors. Things like `AssertStillLive(io.req.ready)` (i.e., things that check that a wire isn't pruned or left floating or checks that a condition is possible).

**Comment by chick** [comment]
@jackkoenig What do you think about converting this to an RFC?

**Comment by azidar** [comment]
Not an issue - decided that we can't catch all of these by solely looking at the expression.
