### ISSUE TITLE
Running coverage under sbt 1.0 does not cover source in chiselFrontEnd

### ISSUE THREAD

**Issue by chick** [freechipsproject/chisel3#772]
* **Type of issue**
  - [X] Bug report
  - [ ] Feature request
  - [ ] Other enhancement

* **Aggregated coverage not working with sbt 1.0**
When trying to get fuller coverage information from chiselFront end, I
change the sbt file to have
`aggregate := true` instead of `aggregate := false`
Then run
`make coverage`
This does not include the chisel.core and other things from chiselFrontend

As a test I went to a version of chisel3 that did not use sbt 1.0
via 
`git checkout 3.0.2`
After doing this the `make coverage` did include chisel.core code

* **What is the use case for changing the behavior?**
We are hoping to improve our coverage, but we are also moving forward on sbt.

* **Impact**
  - [ ] no functional change
  - [ ] API addition (no impact on existing code)
  - [ ] API modification
  - [ ] unknown

* **Other information** *
The following [Compatibility with sbt 1.0 #95](https://github.com/scoverage/sbt-coveralls/issues/95) may be relevant.

**Comment by azidar** [comment]
Sounds like an sbt bug, @ucbjrl will submit a issue to sbt.
