### ISSUE TITLE
 Attaching Analog(X.W) to several Analog(1.W)

### ISSUE THREAD

**Issue by edwardcwang** [freechipsproject/chisel3#784]
Reported by @mwachs5
Migrated from https://github.com/ucb-bar/chisel/issues/748

---

Is there *no* way to connect Analog(x.W) to e.g. a Vec(x, Analog(1.W))?

I would want to use Vec(x, Analog(1.W)) everywhere, except when I connect to a black-box which actually has

```
inout [2:0] foo;
```

then I I need to use 
```
val foo = Analog(3.W)
```
instead of 
```
val foo = Vec(3, Analog(1.W))
```

**Comment by mwachs5** [comment]
Ah.  I need to update my bookmarks!

It was suggested to try inline black box. Giving it a shot.

**Comment by mwachs5** [comment]
I was able to make something work with `HasBlackBoxInline`.

**Comment by chick** [comment]
Dup of #536
