### ISSUE TITLE
Return in When statement causes exciting bugs and error messages

### ISSUE THREAD

**Issue by mehnadnerd** [freechipsproject/chisel3#841]
**Type of issue**: bug report/feature request

**Impact**: API addition (no impact on existing code)

**Development Phase**: request

**Other information**
 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**
Code sample:
```scala
def safeAccess(): UInt = {
  when(cacheUsable) {
    return reqCache.data
  }
  return io.req.data.bits
}
```
**What is the current behavior?**
Currently, this fails during elaboration, with the error message "Internal Error! When depth is != 0, this should not be possible".
This can be fixed with the below, under "Expected behaviour".

**What is the expected behavior?**
There are two possibilities: Either this is the wrong way to do it, and the correct way is:
```scala
def safeAccess(): UInt = {
  val temp = Wire(UInt())
  when(cacheUsable) {
    temp := reqCache.data
  } .otherwise {
    temp := io.data.bits
  }
  temp
}
```
or this should be allowed. (Is a Mux the correct option? This should compile to the same as one)
If this is the wrong way (which I think is likely), then it would be helpful to have a better error message and/or guidance that this is the wrong way to do it.

**Please tell us about your environment:**
a6

**What is the use case for changing the behavior?**
Easier use of functions for convenience.

**Comment by edwardcwang** [comment]
Just for curiosity, what is the behaviour of the following?

```scala
def safeAccess(): UInt = {
  when(cacheUsable) {
    return reqCache.data
  } .otherwise {
    return io.req.data.bits
  }
}
```

Not sure on whether or not return in when() is intended to be allowed, but `Mux()` seems to be a good fit for your usecase.

**Comment by mehnadnerd** [comment]
That won't compile, Scala doesn't recognise that the when ... .otherwise covers all cases and so doesn't know a UInt will be returned

**Comment by mehnadnerd** [comment]
Results from Chisel-Dev Meeting:
put quotes around the ‘when’ in the error message, add a probable cause diagnosis, the correct way to do this is a mux, remove the ‘this isn’t possible’
return in when is not allowed, need to make it clear that this isn't the right way, use mux instead
