### ISSUE TITLE
Windows  Compatibilty.

### ISSUE THREAD

**Issue by ankitkk** [freechipsproject/chisel3#874]
The Scala side of things work seamlessly. The most annoying part - is getting Verilator to work on windows. 

https://github.com/ankitkk/VerilatorWindows  ( initial work from @baughg )  builds veritilator for windows correctly.  I intend to keep this sync'd with mainline verilator. The real solution is to push for a CMake build upstream and remove their reliance on autotools.

**Comment by frozenspider** [comment]
Can I get a pre-compiled version for Windows from somewhere?

**Comment by ankitkk** [comment]
try https://github.com/ankitkk/VerilatorWindows/releases

**Comment by frozenspider** [comment]
But there are no releases (or even tags), or am I missing something?

**Comment by ducky64** [comment]
While chisel uses verilator as the default simulator, chisel-only designs (that don't have blackboxes) can be simulated in either firrtl-interpreter or treadle. This will (probably) be the default testing backend in the new testing infrastructure (#725 - it's while away though), so the stack should be fully Scala. In addition to fixing cross-platform issues, it also reduces the startup time (verilator + compilation is pretty slow) which makes it more suitable for lots of small unit tests.

That being said, if you have a good and easy setup for running verilator on Windows, we could certainly reference it as an option in our documentation. Personally, I'd like to see something that fits the typical workflow of Windows users: a precompiled binary and installer (I don't think building-from-source is common among Windows users). Maybe with a MSVC Express or a MinGW dependency, but preferably not something that provides a Linux-like environment like cygwin - in which case you might as well go full WSL and follow the Linux setup instructions.

**Comment by ducky64** [comment]
Closing: not our bug, Verilator needs better support upstream. We're also planning to run treadle, a Scala-based FIRRTL simulator, by default for 3.3, so chisel tests will work on Windows out of the box.

Feel free to re-open or create a new issue if you have a good path to Verilator working well natively on Windows, and we can update our docs.
