### ISSUE TITLE
I still got the error message "edu.berkeley.cs#firrtl_2.12;1.2-SNAPSHOT: not found" after publishLocal firrtl

### ISSUE THREAD

**Issue by PAIWANG94** [freechipsproject/chisel3#879]

**Comment by ucbjrl** [comment]
I suspect your versions of firrtl and chisel3 are inconsistent. We recently switched the default Scala version for both from 2.11 to 2.12. Make sure you're on the master branch for both and do a `git pull` to ensure they're up-to-date.

Alternatively, you can:
```bash
sbt +publishLocal
```
which will publish all cross versions (both Scala 2.11 and Scala 2.12 currently).

**Comment by qiner199** [comment]
I update the build.sbt file with  
resolvers ++= Seq(
    Resolver.sonatypeRepo("snapshots"),
    Resolver.sonatypeRepo("releases")
  )
worked successful !! you can have a try

**Comment by jackkoenig** [comment]
I believe that changing the resolvers is grabbing the published snapshots, not using a locally published version.

If you want to publish locally and use that one, you should use `sbt +publishLocal`
