### ISSUE TITLE
Can't set DontCare for Analog wires using bulk connect (<>)

### ISSUE THREAD

**Issue by edwardcwang** [freechipsproject/chisel3#882]
**Type of issue**: bug report

**Impact**: API addition (no impact on existing code)?

**Development Phase**: request

Trying to set an Analog wire to `DontCare` using `<>` causes an error. Example:

```scala
import chisel3._
import chisel3.experimental._
class AnalogDontCareTestModule extends Module {
 val io = IO(new Bundle {
   val out = Vec(2, Analog(1.W))
   val in = Analog(1.W)
 })
 io.out(0) <> io.in
 io.out(1) := DontCare
 // io.out(1) <> DontCare // <-- doesn't work
}
```

Error message:

```
java.lang.RuntimeException: Unexpected port element direction 'Bidirectional(Default)'
  chisel3.core.BindingDirection$.from(Binding.scala:66)
  chisel3.core.BiConnect$.elemConnect(BiConnect.scala:216)
  chisel3.core.BiConnect$.connect(BiConnect.scala:68)
  chisel3.core.Data.bulkConnect(Data.scala:322)
  chisel3.core.Data.$less$greater(Data.scala:366)
```

This is strange as a user since `:=` is generally verboten for `Analog` but I'm forced to use `:=` for DontCare on Analog. It seems natural to allow `Analog`s to be set to `DontCare` using `<>`.

**Comment by redpanda3** [comment]
I suggest to delete <>, since <> and := are the same function within a data...
