### ISSUE TITLE
sbt compile error

### ISSUE THREAD

**Issue by MikuChaser** [freechipsproject/chisel3#924]
OS: Ubuntu 16.04
Problem: Can't use chisel 3.2+
Description: I have installed the newest version of sbt, firrtl and verilator. When I created my project under the folder  chisel-template or chisel-tutorial, the project can work. However, using the chisel3 repository is wrong. When I run "sbt compile", it shows:
`[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/wubin/chisel-workspace/chisel3/project
[info] Loading settings from build.sbt ...
[info] Set current project to chisel3 (in build file:/home/wubin/chisel-workspace/chisel3/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Updating coreMacros...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: edu.berkeley.cs#firrtl_2.12;1.2-SNAPSHOT: java.text.ParseException: [unknown tag project in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag modelVersion in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag groupId in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag artifactId in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag packaging in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag description in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag version in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag name in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag organization in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag name in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag scm in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag url in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag connection in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag developerConnection in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag url in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag licenses in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag license in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag name in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag url in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag distribution in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag developers in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag developer in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag id in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag name in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] , unknown tag url in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[warn] ]
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		edu.berkeley.cs:firrtl_2.12:1.2-SNAPSHOT
[warn] 		  +- edu.berkeley.cs:coremacros_2.12:3.2-SNAPSHOT
[error] sbt.librarymanagement.ResolveException: unresolved dependency: edu.berkeley.cs#firrtl_2.12;1.2-SNAPSHOT: java.text.ParseException: [unknown tag project in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag modelVersion in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag groupId in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag artifactId in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag packaging in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag description in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag version in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag name in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag organization in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag name in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag scm in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag url in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag connection in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag developerConnection in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag url in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag licenses in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag license in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag name in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag url in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag distribution in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag developers in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag developer in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag id in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag name in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag url in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] ]
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2383)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (coreMacros / update) sbt.librarymanagement.ResolveException: unresolved dependency: edu.berkeley.cs#firrtl_2.12;1.2-SNAPSHOT: java.text.ParseException: [unknown tag project in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag modelVersion in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag groupId in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag artifactId in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag packaging in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag description in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag version in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag name in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag organization in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag name in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag scm in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag url in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag connection in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag developerConnection in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag url in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag licenses in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag license in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag name in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag url in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag distribution in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag developers in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag developer in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag id in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag name in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] , unknown tag url in file:/home/wubin/.ivy2/cache/edu.berkeley.cs/firrtl_2.12/ivy-1.2-SNAPSHOT.xml.original
[error] ]
[error] Total time: 6 s, completed Nov 3, 2018 2:00:17 PM
`
What should I do?

**Comment by seldridge** [comment]
If you're trying to build Chisel locally (which is generally unnecessary unless you're doing development on the repo), you need to have published a local snapshot of the FIRRTL repository. Inside the FIRRTL reposotiory run `sbt publishLocal`. This puts all the FIRRTL jars in ~/.ivy2.

The reason why chisel-template works is that that is pulling directly from Maven. The Chisel repository is configured to use your local snapshot of FIRRTL as this makes the most sense for developer work that would be contributed back upstream.

**Comment by MikuChaser** [comment]
> If you're trying to build Chisel locally (which is generally unnecessary unless you're doing development on the repo), you need to have published a local snapshot of the FIRRTL repository. Inside the FIRRTL reposotiory run `sbt publishLocal`. This puts all the FIRRTL jars in ~/.ivy2.
> 
> The reason why chisel-template works is that that is pulling directly from Maven. The Chisel repository is configured to use your local snapshot of FIRRTL as this makes the most sense for developer work that would be contributed back upstream.

Of course. According to the readme of the Chisel3, I have installed the firrtl.
![image](https://user-images.githubusercontent.com/28176235/47953540-15f3a400-dfba-11e8-86dd-580368e20e29.png)
Firstly, I git from the repo. Then, run "sbt compile" and it's successful. But "sbt test" failed. "sbt assembly" and "sbt publishLocal" also work.

**Comment by MikuChaser** [comment]
I have solved it. Just delete the old .ivy2 folder.

**Comment by seldridge** [comment]
Closing this as it looks like you have a solution. Feel free to re-open if that's not the case.
