### ISSUE TITLE
Wiki Cookbook -> Vec(elts) is deprecated, use VecInit(elts) instead

### ISSUE THREAD

**Issue by Martoni** [freechipsproject/chisel3#928]
**Type of issue**: bug report

**Impact**: no functional change

**Development Phase**: request 

**Other information**
Documentation wiki
 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

I don't know how to «pull request» a patch for the wiki, but in cookbook page I think the example for vec of registers initialisation is obsolete (I tested it and chisel3 complain about it) : 
on chapter [«how-do-i-create-a-reg-of-type-vec»](https://github.com/freechipsproject/chisel3/wiki/Cookbook#how-do-i-create-a-reg-of-type-vec) the line : 
`  val initRegOfVec = RegInit(Vec(Seq.fill(4)(0.U(32.W))))`
Should be
`  val initRegOfVec = RegInit(VecInit(Seq.fill(4)(0.U(32.W))))`

No ?

**Comment by edwardcwang** [comment]
Fixed. Thanks for the catch!
