### ISSUE TITLE
[RFC] Define Policy for Ensuring Binary Compatibility

### ISSUE THREAD

**Issue by jackkoenig** [freechipsproject/chisel3#942]
As proposed by a talk I attended at Scale By the Bay, there is a tool for this from Lightbend: https://github.com/lightbend/migration-manager

We should include this (and source compatibility checking as well) as part of our CI.

**Type of issue**: other enhancement

**Impact**: no functional change

**Development Phase**: request

**Other information**
 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

**What is the current behavior?**

We just think really hard and hope we're preserving binary compatibility. We check source compatibility by compiling against rocket-chip and other libraries, but I don't think we even try to check binary compatibility

**What is the expected behavior?**

We should adhere to the compatibility we claim in our versioning.

**Please tell us about your environment:**

**What is the use case for changing the behavior?**

A better and more robust library!

**Comment by jackkoenig** [comment]
The talk: https://speakerdeck.com/seratch/5-tips-to-build-long-lasting-scala-oss
Related template: https://github.com/seratch/long-lasting-scala.g8

**Comment by ucbjrl** [comment]
We should also look at: 
- [swagger](https://swagger.io/), https://github.com/hootsuite/sbt-swagger
- [OpenAPI](https://github.com/OAI/OpenAPI-Specification)
Although the latter is aimed at REST API's, there may be some useful tools/techniques we can adapt.

**Comment by azidar** [comment]
Done!
