### ISSUE TITLE
Can't find field of aggregate Memory in nested Module

### ISSUE THREAD

**Issue by nhynes** [freechipsproject/chisel3#971]
**Type of issue**: bug report

**Impact**: no functional change

**What is the current behavior?**

**Pseudo-MWE**

```scala
class MyModule extends Module {
  val io = IO(...)
  val mem = SyncReadMem(42, new Bundle {
    val a = Bool()
    val b = Bool()
  })
}

class Top extends Module {
  val io = IO(...)
  val mm = Module(new MyModule)
}

// in TopTest.scala
class TestingTop extends Top {
  loadMemoryFromFile(mm.mem, "memfile")
  // annotation could also go in MyModule itself but gives the same error
}
```

Compiling this yields the following error

```
java.util.NoSuchElementException: key not found: MyModule.mem_b
...
...
at treadle.executable.MemoryInitializer.$anonfun$memoryMetadata$1(Memory.scala:614)
```

For some reason `mem_a` is found? I wonder if I'm not running into DCE since it works fine when `MyModule` is the Top.

**What is the expected behavior?**

It should Just Work (TM).

**Please tell us about your environment:**

`master` branch of all relevant repos (including `chisel-testers2` since that seems to be relevant)

**Comment by nhynes** [comment]
Yep. DCE FTW. Sorry for the spam.

**Comment by Croyyin** [comment]
> Yep. DCE FTW. Sorry for the spam.
> 
> For reference, a quick and dirty fix is to just
> 
> ```scala
> ptionsManager.firrtlOptions.annotations :+ firrtl.transforms.NoDCEAnnotation
> ```

I'm sorry to disturb you, but I wonder where I should use ''ptionsManager.firrtlOptions.annotations :+ firrtl.transforms.NoDCEAnnotation''.

**Comment by wubinyi** [comment]
> > Yep. DCE FTW. Sorry for the spam.
> > For reference, a quick and dirty fix is to just
> > ```scala
> > ptionsManager.firrtlOptions.annotations :+ firrtl.transforms.NoDCEAnnotation
> > ```
> 
> I'm sorry to disturb you, but I wonder where I should use ''ptionsManager.firrtlOptions.annotations :+ firrtl.transforms.NoDCEAnnotation''.


You can do it like the following code.

import org.scalatest._
import chiseltest._
import chisel3._
import chiseltest.experimental.TestOptionBuilder.ChiselScalatestOptionBuilder
import chiseltest.internal.TreadleBackendAnnotation
import firrtl.transforms.NoDCEAnnotation

class myModuleTests extends FlatSpec with ChiselScalatestTester with Matchers {
	behavior of "my module"
	
	it should("do something") in {
		val annotations = Seq(
			TreadleBackendAnnotation,
			NoDCEAnnotation
		)
		test(new MyModule()).withAnnotations(annotations) {dut =>
                        // "write your test"
		}
	}
}
