### ISSUE TITLE
How to push Rocket to use local FIRRTL and Chisel ?

### ISSUE THREAD

**Issue by tampler** [freechipsproject/chisel3#973]
Rocket ships with predefined Chisel and FIRRTL versions. The same is true for all other IP repos, such as boom, fire, etc

I'd like to test my own versions. I did **sbt publishLocal** for both dependencies. Now, how do I push Rocket to use them ?

**Comment by edwardcwang** [comment]
This appears to be a rocket-chip question so I'm going to go ahead and close this issue for now. Please see:

https://github.com/freechipsproject/rocket-chip/issues/1621

https://github.com/freechipsproject/rocket-chip/pull/1246
