### ISSUE TITLE
Inconsistent printf with firrtl backend

### ISSUE THREAD

**Issue by immesys** [freechipsproject/chisel3#993]
**Type of issue**: bug report 

I am seeing mind-boggling printf statement when I simulate with the FIRRTL backend.

The following excerpt:
```
var y = Wire(UInt(10.W))
var regY = RegNext(y)
var regRegY = RegNext(regY)
...
when (regRegY === 480.U) {
   printf("+++ ry=%x isZero=%x is480=%x\n", regRegY, regRegY === 0.U, regRegY === 480.U);
}
```
Prints

```
+++ ry=0 isZero=0 is480=1
```

This doesn't seem to happen with Verilator as a backend.

I don't know what sort of information would be useful here, if someone can let me know what sort of thing could cause this I can try work it out.

**Comment by chick** [comment]
I believe this is a dependency ordering problem in the interpreter. I don't think it is a problem with the *treadle* backend. I will add to my list to test and fix.

**Comment by chick** [comment]
Contrary to what I said earlier, I can only reproduce this with treadle. (Though it still might be the case that the interpreter can have the problems). I have created [/freechipsproject/treadle/pull/81](/freechipsproject/treadle/pull/81). It includes a test in PrintStopSpec at the end that is my extrapolation of the problem described above

**Comment by ucbjrl** [comment]
@chick - can we close this?

**Comment by chick** [comment]
I think we can close it. Treadle is the supported scala backend.
